site_name: SRAMPlatform
repo_url: https://github.com/servinagrero/SRAMPlatform
repo_name: SRAMPlatform
edit_uri: ""
theme:
    logo: img/logo.png
    name: material
    palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primary: deep purple
          accent: light blue
        - scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
          primary: white
          accent: dark blue
    font:
        text: Roboto
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.sections
        - navigation.expand
        - toc.integrate
        - content.code.annotate

extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
  - autorefs
  - mkdocstrings
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  
nav:
    - Introduction: index.md
    - Getting started: starting.md
    - Platform:
        - Description: description.md
        - Platform API: platform_api.md
    - TIMA Station:
        - Information: tima.md
        - Implementation:
            - Communication: communication.md
            - Devices: devices.md
            - Storage: database.md
            - Logging: logging.md
            - Code Execution: code_exec.md
        - Available commands: commands.md
        - Deployment: deployment.md
        - Code Reference:
            - Platform API: tima_api.md
            - Device API: device_api.md
    

